from fieldtrip._runtime import Runtime


def _read_brainstorm_data(*args, **kwargs):
    """
      READ_BRAINSTORM_DATA reads .EEG files that have been generated by
        the Nihon Kohden system. The function constitutes a wrapper around
        BrainStorm3 functionalities

        Use as
          [dat] = read_brainstorm_data(filename, hdr, begsample, endsample, chanindx)

        The function has not been tested on NK1200 files with multiple epochs

        See also READ_BRAINSTORM_HEADER, READ_BRAINSTORM_EVENT


    This file was automatically converted from Matlab to Python using
    [MPython](https://github.com/MPython-Package-Factory/mpython), please
    refer to the original matlab file for the most accurate documentation.

    [Matlab code]( https://github.com/fieldtrip/fieldtrip/blob/master/fileio/private/read_brainstorm_data.m )

    Copyright (C) 2011-2021, Robert Oostenveld
    Copyright (C) 2022-, Jan-Mathijs Schoffelen and Robert Oostenveld

    This file is part of FieldTrip, see http://www.fieldtriptoolbox.org
    for the documentation and details.

    FieldTrip is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    FieldTrip is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with FieldTrip. If not, see <http://www.gnu.org/licenses/>.
    """

    return Runtime.call("read_brainstorm_data", *args, **kwargs)
